#!/bin/sh

# This script checks for valid commit messages.

# Regex pattern for a valid commit message
commit_regex='^(feat|fix|docs|style|refactor|perf|test|chore|BREAKING CHANGE): .{1,50}'

error_msg="ERROR: Commit message does not follow the conventional format.
Example: 'feat: add new feature'

Allowed types:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation changes
  - style: Code style changes (formatting, missing semicolons, etc.)
  - refactor: Refactoring code (neither new feature nor bug fix)
  - perf: Performance improvements
  - test: Adding or updating tests
  - chore: Changes to the build process or auxiliary tools and libraries
  - BREAKING CHANGE: A major change that affects backward compatibility

Your commit message:
$(head -n1 $1)"

commit_msg=$(cat "$1")

if ! echo "$commit_msg" | grep -iqE "$commit_regex"; then
  echo "$error_msg"
  exit 1
fi
