name: PR Checks

on:
  pull_request:
    types: [opened]

    
jobs:
  Linting:
    name: Linting with super linter
    permissions:
      contents: write
      packages: write
      statuses: write
    uses: ./.github/workflows/linting.yml
  Sonar:
    name: Code scan with sonarqube
    uses: ./.github/workflows/sonar.yml
    